### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vegarringdal** [mframejs/mframejs#2]
Small list on stuff I want to try and make
Most parts of whats done need more work, rebuild to work better

- [x] Custom Attributes 
  - [x] **(needs on router configure (not existing, ony main app)** 
- [x] Custom Element
- [x] interpolate text
- [ ] custom View (like custom element, just it becomes part of parent, so just a loadTemplate, its possible to just use any html file, but would be usefull if this was seperate containerclass

**Built in Attributes:**
- [x] if.bind 
     - [ ] look at template tag as option (can not be used with repeat on same element)
- [x] show.bind
- [x] disabled.bind
- [x] checked.bind
- [x] css.bind 
  - [ ] needs more work, need to remove if expression removes/undefined/null
- [x] value.bind
- [x] repeat.for 
  - [ ] look at template tag as option (can not be used with repeat on same element)
- [x] click.trigger/delegate (delegate is not delegate, just event listener on element atm)
- [x] readonly.bind
- [x] class.bind
  - [ ] class.bind replace all, need one that mire dynamic only add/remove from expression
- [x] trigger.on (for inputs) combine this with value.bind
- [x] select/option with multiple  (page 5 inn sample)
- [x] checkbox group & radio button group ( page 5 in sample)

Build in Elements
 - [x] router  
   - [ ] needs more work, single router atm, needs child router, more options
   - [ ] configureRouter custom attribute is not called in lifecycle atm (just when configure main app class)
   - info - code splitting of routes work very well with fusebox 3.0**

Binding
- [x] basic binding with expressions
- [x] override context 
   - info: repeat adds by it self, for custom in attribute/element user needs to add property `overrideContext`, something like $parent 

**binding behavior**
Most added need some refactor, and more structure so other can use better
- [x] trigger:blur 
- [x] debounce: 200?
- [x] throttle: 200?
- [x] signal, now you can do like this
   - info `${someVar & signal:'cool'}` <- this will now listen for "signal-cool" channel in the eventAggregator
useful for 

**Decorator**
- [x] @inject
    - consider ? cant inject parent etc, would be useful for attributes/child view
- [x] @customAttribute
- [x] @customElement
- [x] @valueConverter
- [x] @transient
- [x] @bindable
- [x] @computeFrom
- [x] @observe
 - [ ] @autoInject (wonder how this even works, I prb need some metadata poly-fill /lib)
Skeleton/demo
- [x] simple with ghpages option

**Other:**
- [x] look at https://github.com/krausest/js-framework-benchmark/ and make skeleton, to use as test base (this will also clear iut mini bugs in repeat.for 
 - [X] db monster -https://github.com/mframejs/mframejs-dbmonster
-  [x] skeleton nav https://github.com/mframejs/mframejs-skeleton
-  [x] skeleton empty  https://github.com/mframejs/mframejs-skeleton-empty
- consider ? SSR ? how much rewrite do I need, atm its just a client side framework
- consider ? no way for one time binding, this could improve memory when doing a lot, like db-monster (no prio at all)
- [ ] use fusebox runner on expression testing, and add ore expression tests (would have been very useful with more tests, only have on expression in sample atm)
- [x] start on docs- https://github.com/mframejs/mframejs-docs

**Comment by vegarringdal** [comment]
add option for using `<template>` tags with if.bind/repeat
Note to my self, using template tag will kill repeat reference to template
